#!/bin/sh
set -e
# Automatically added by dh_makeshlibs
if [ "$1" = "remove" ]; then
	ldconfig
fi
# End automatically added section
rm /opt/ros/fuerte/include/ompl
rm /opt/ros/fuerte/include/omplext_odeint
